"""
User model.

The users table stores account identity, profile metadata, and a password hash.
Raw passwords are never persisted; only Werkzeug-generated hashes are stored.
"""

from __future__ import annotations

from flask_login import UserMixin
from werkzeug.security import check_password_hash, generate_password_hash

from expense_tracker.extensions import db


class User(UserMixin, db.Model):
    """
    SQLAlchemy model used by Flask-Login to represent an authenticated account.
    """

    __tablename__ = "users"

    # Primary key is used in sessions and password-reset tokens.
    id = db.Column(db.Integer, primary_key=True)

    # Full name gives the UI a human-readable account label.
    full_name = db.Column(db.String(120), nullable=False)

    # Email is the unique login identifier and reset-password destination.
    email = db.Column(db.String(255), unique=True, nullable=False, index=True)

    # Phone number is optional contact metadata collected during registration.
    phone_number = db.Column(db.String(30), nullable=True)

    # Username remains for compatibility with existing relationship/UI code.
    username = db.Column(db.String(255), unique=True, nullable=False, index=True)

    # Password hash stores the protected credential generated by Werkzeug.
    password_hash = db.Column(db.String(256), nullable=False)

    # Transactions are owned by one user and removed if the account is deleted.
    transactions = db.relationship(
        "Transaction",
        backref="owner",
        lazy="dynamic",
        cascade="all, delete-orphan",
    )

    def set_password(self, password: str) -> None:
        """
        Hash a raw password before storing it on the model.

        Keeping hashing inside the model ensures registration and reset flows
        cannot accidentally persist plaintext credentials.
        """

        self.password_hash = generate_password_hash(password)

    def check_password(self, password: str) -> bool:
        """
        Compare a raw password with the stored password hash.

        Werkzeug performs the safe hash verification so routes never implement
        credential comparison manually.
        """

        return check_password_hash(self.password_hash, password)
