"""add sub_category column to transactions

Revision ID: 91311257c55f
Revises: 2d97c0efc64d
Create Date: 2026-06-15 09:15:26.267482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91311257c55f'
down_revision = '2d97c0efc64d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('limit_amount', sa.Float(), nullable=True))
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_budgets_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_month'), ['month'], unique=False)
        batch_op.create_index(batch_op.f('ix_budgets_user_id'), ['user_id'], unique=False)
        batch_op.create_unique_constraint('uq_budget_user_month_category', ['user_id', 'month', 'category'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sub_category', sa.String(length=80), nullable=True))
        
        # Server defaults keep existing transaction rows valid during migration.
        batch_op.add_column(sa.Column('currency_code', sa.String(length=3), server_default='PKR', nullable=False))
        batch_op.add_column(sa.Column('exchange_rate', sa.Float(), server_default='1.0', nullable=False))
        
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=80),
               existing_nullable=False)
        batch_op.create_index('ix_transactions_user_category_subcategory', ['user_id', 'category', 'sub_category'], unique=False)
        batch_op.create_index('ix_transactions_user_type_date', ['user_id', 'entry_type', 'entry_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_transactions_user_type_date')
        batch_op.drop_index('ix_transactions_user_category_subcategory')
        batch_op.alter_column('category',
               existing_type=sa.String(length=80),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
        batch_op.drop_column('exchange_rate')
        batch_op.drop_column('currency_code')
        batch_op.drop_column('sub_category')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_constraint('uq_budget_user_month_category', type_='unique')
        batch_op.drop_index(batch_op.f('ix_budgets_user_id'))
        batch_op.drop_index(batch_op.f('ix_budgets_month'))
        batch_op.drop_index(batch_op.f('ix_budgets_category'))
        batch_op.alter_column('amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
        batch_op.drop_column('limit_amount')
        batch_op.drop_column('category')

    # ### end Alembic commands ###
